

export const REGISTRATION_COMMIT = "REGISTRATION_COMMIT"


export const USER_REGISTRATION_START = "USER_REGISTRATION_START"
export const USER_REGISTERED_FAIL = "USER_REGISTERED_FAIL"
export const USER_REGISTERED_SUCCES = "USER_REGISTERED_SUCCES"
export const USER_LOG_OUT = "USER_LOG_OUT"
export const USER_LOGIN_SUCCES = "USER_LOGIN_SUCCES"

export const WeightIdata = "WeightIdata"
